### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cetepek** [Writech/node-red-contrib-controltimer#11]
Im using trigger node to control my motion sensor - light flow. The problem is that I can't control the delay of the trigger node by message. I noticed that your controltimer node would do the same and your to do list has the option of control the timer by message. Is that option coming any time soon?

**Comment by habnefrage** [comment]
I would wote for this feature, too.

Would be great to be able to set the duration via msg.payload or something else.

**Comment by cetepek** [comment]
I found solution to do this with the trigger node. My goal was to be apple to change how long my lights are on after motion sensor didnt see any motion from my home assistants dashboard / lovelace. For the dashboard control I made input number boolean and in the nodered flow I use current state node to check the input number value and with range node change it from min to ms and change the message msg.delay. After that comes trigger node. Trigger node has option to "override delay with msg.delay" And thats it. Hope it helps.

**Comment by Jens5395** [comment]
I am using the node in a subflow. Instead of a fixed 'timer duration' number, it would be great if the field input was not limited to a numeric input. In other words, it would be great if, for the 'timer duration' field, I could enter ${delay} instead of a number. While ${delay} would evaluate to a number, because the input field only allows a numeric value, it will ignore the attempts of entering the environmental variable.

**Comment by jmrassuncao** [comment]
+1 for changing Timer Duration with an input!

**Comment by Writech** [comment]
Configuring controltimer by sending it a message with type, duration and duration unit is now implemented in v0.2.0 release. Check the README for more info.
