### ISSUE TITLE
Loop Mode ?

### ISSUE THREAD

**Issue by steerage250** [Writech/node-red-contrib-controltimer#32]
It is unclear to me what Loop mode does (as distinct to Delay) mode.  Maybe some more words (and maybe an example) are warranted in your "help file" ?

Also, I thought I needed Loop mode (but I don't think I did), and when using it in Loop mode, I only got an event when the initial time expired on the 2nd output (compared to the first output when using it in Delay mode).

**Comment by Writech** [comment]
**Delay mode:** Timer will emit one event via `timer-triggered` output after the specified delay expires.
**Loop mode:** Timer will keep emitting events indefinitely via `timer-triggered` output with specified interval.

Event is emitted via `timer-halted` output if `STOP` or `PAUSE` payload is sent to the timer.

**Comment by steerage250** [comment]
Thanks, that is what I expected, however, what I don't expect is by changing the timer from Delay to Loop, that the initial timer time-out event switched from the 1st output to the 2nd output.  As a Delay timer, after 10 seconds, I get a "Timer Triggered" debug message from output 1.  If I then change the timer type to Loop, after 10 seconds, I get the "Timer Halted" debug message from output 2.

![image](https://github.com/Writech/node-red-contrib-controltimer/assets/27069902/3d78191d-13bb-4258-a8df-f9e3e49a4067)

**Comment by Writech** [comment]
I'm not exactly sure what the issue is still. Can you produce exact steps to replicate the problem you're encountering?

What I tried so far:
- Using the config panel configure controltimer with `5 second delay`.
- Start the timer.
- Timer expires and an event is sent to `timer-triggered` output.
- Start the timer again.
- After ~2.5 seconds send an override config message configuring the timer to run in `5 second loop` mode.
- Timer restarts with `5 second loop` mode and it didn't emit an event to `timer-halted` output.
- Timer expires the first time and an event is sent to `timer-triggered` output. All the succeeding loop expiries also send an event to `timer-triggered` output.
- Only when I manually send `STOP` payload an event is sent to `timer-halted` output.

What I also tried:
- Using the config panel configure controltimer with `5 second delay`.
- Start the timer.
- Timer expires and an event is sent to `timer-triggered` output.
- Using the config panel configure controltimer with `5 second loop`.
- Deploy changes.
- Start the timer.
- Timer expires and an event is sent to `timer-triggered` output and all the succeeding loop expiries also send an event to `timer-triggered` output.
- Only when I manually send `STOP` payload an event is sent to `timer-halted` output.

**Comment by steerage250** [comment]
I do what you do in your second example, but with different results.
This first screenshot shows a Delay timer expiring and sending an event to the top output - as expected.
![controltimer delay example](https://github.com/Writech/node-red-contrib-controltimer/assets/27069902/460484e5-e1af-4902-9040-934022d4ed43)
I then reconfigure the timer as a Loop timer and deploy (as per this screenshot):
![controltimer loop configuration](https://github.com/Writech/node-red-contrib-controltimer/assets/27069902/f44c96e5-9c3a-46d4-a7f9-770483b57cd7)
- and I get a LOOP_TIMEOUT message sent to the lower output as per the next screenshot -and the timer does not keep looping (it Stops and reverts to idle)
![controltimer loop example](https://github.com/Writech/node-red-contrib-controltimer/assets/27069902/1245d3d4-f0af-44d8-acb4-4868c44fb8d0)

**Comment by Writech** [comment]
You are getting `LOOP_TIMEOUT` message to the `timer-halted` output because you have set `Loop timeout` to 5 seconds. Using the `Loop timeout` setting you can limit the timer with a specified duration after which is should time out and stop. If you set Loop timeout to 0, as it is by default you will not get the the LOOP_TIMEOUT message.

**Comment by steerage250** [comment]
ah! now I understand.  I did not understand what the Loop_Timeout was for.  It is maybe another thing that could be put into some expanded description in the help file :-)
thanks

**Comment by steerage250** [comment]
I now have an application where I would like to use the Loop mode (I think), but I don't understand how it works.  What I need is 9 outputs/messages produced from one trigger event.  Is this possible?

I tried setting the timer to 5 secs, and the loop timeout to 1 sec with a max iterations of 9.  However, it just times-out after 5 seconds and doesn't do any looping.  

When/how does it loop ?

thanks
Ian

**Comment by steerage250** [comment]
ah - I got it to work: timer duration of 1 second, then a big loop timeout with a max iteration counter of 9 
all good
thanks
